spring:
  datasource:
    #url: jdbc:mysql://mysqldb:3306/usersdb
    url: jdbc:mysql://localhost:3306/task-man-db
    username: user
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      format_sql: true;
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

  application:
    name: identity-provider

  profiles:
        active: docker


server:
  port: 8089

  error:
    include-message: ALWAYS
    include-binding-errors: ALWAYS

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
      #defaultZone: http://eureka-server:8010/eureka

super:
  admin:
    username: admin
    password: password

springdoc:
  swagger-ui:
    path: /api/v1/pub/swagger-ui.html
  api-docs:
    path: /api/v1/pub/api-docs




